### ISSUE TITLE
Same type

### ISSUE THREAD

**Issue by virzak** [Ne4to/N.SourceGenerators.UnionTypes#26] opened 2023-10-10 16:57 UTC
Is it possible to implement DU with properties of the same type?

```cs
[UnionType(typeof(int), "MyInt")]
[UnionType(typeof(int), "MyOtherInt")]
public partial struct MyStruct {}
```

**Comment by Ne4to** [comment] 2023-10-12 17:46
No, it is not possible.
The issue is that after adding UnionType attribute to MyStruct it will contain .ctor, implicit and explicit operator to the specified type and there is no way to distinguish MyInt from MyOtherInt.

Could you give an example why you need the same type with different name?

My assumption is that you need it for some kind of Id type.
In this case I propose specify these types explicitly.
```csharp
public readonly record struct OrderId(int Value)
{
    public override string ToString()
    {
        return Value.ToString();
    }

    public static implicit operator int(OrderId orderId)
    {
        return orderId.Value;
    }
}

[UnionType(typeof(OrderId))]
public partial struct MyStruct {}
```

**Comment by fedele7008** [comment] 2023-10-13 14:44
We are want to use DU to store some sample number of the data OR some timestamp value of the data, and both happens to be integer type (and there are more different types stored in this DU). So we wanted to differentiate between sample int type and timestamp int type.

**Comment by Ne4to** [comment] 2023-10-17 18:07
I still propose to wrap timestamp into a struct.
It can be used like Int32 but this way you never mix up MyInt and MyOtherInt.
```csharp
public readonly record struct Timestamp(int Value);
```

If it is not suitable, we need to think about public API change for union type in case of using the same type multiple times.
New static methods should replace the use of contstructors.
```diff
- public MyStruct(int value) // can't distinguish MyInt from MyOtherInt
+ public static MyStruct FromMyInt(int value)
+ public static MyStruct FromMyOtherInt(int value)
```

**Comment by fedele7008** [comment] 2023-10-23 21:24
Okay I think it is good. We can close the issue.

**Closed** 2023-10-23 21:32 UTC
